version: '3'

services:
  
  front-end:
    build: 
      context: ./
      dockerfile: ./frontend/docker/Dockerfile
    command: npm run dev
    ports:
      - "3000:3000"
    volumes:
      - "./frontend:/usr/app/frontend"

  back-end:
    build: 
      context: ./
      dockerfile: ./backend/docker/Dockerfile
    command: npm run dev
    ports:
      - "5000:5000"
    volumes:
      - "./backend:/usr/app/backend"